# Permalinks
permalink:           pretty

# Setup
title:               Tahmid Chowdhury  
tagline:             Let's Get Visual
url:                 http://duodecimalstrom.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Tahmid Chowdhury
  url:               http://duodecimalstrom.github.io
  email:             tahmid.chowdhury@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/duodecimalstrom

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
